title:
  full: Coffee Jam Party
  short: Cojam
  short_ru: Коджем

domain: cojam.ru

prime_color: '#8e1214'

dirs:
  dev: source
  build: build
  dist: dist
  dist_content: dist_content
  assets: assets

trackers:
  google: UA-41033513-3
  yandex: 22438144
